services:
  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: matma
      POSTGRES_PASSWORD: matma
      POSTGRES_DB: matma
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
